version: '2.1'

services:

  test:
    image: ortussolutions/commandbox:3.6.0-snapshot
    environment:
      cfconfig_adminPassword: testing
    volumes:
      - ./test:/app
    ports:
      - "8080:8080"